### ISSUE TITLE
你好。有支撑pod install 吗？？

### ISSUE THREAD

**Issue by guobin510** [QuintGao/GKNavigationBar#1]

**Comment by QuintGao** [comment]
支持啊

**Comment by guobin510** [comment]
pod search GKNavigationBar   

找不到只能找到：GKNavigationBarViewController

**Comment by QuintGao** [comment]
请先使用pod update更新本地repo

**Comment by guobin510** [comment]
更新了也搜索不到。只能搜索到  GKNavigationBarViewController

请问。有微信/QQ群吗？？

**Comment by QuintGao** [comment]
有可能是pod搜索的问题，你直接pod进项目是可以用的

**Comment by QuintGao** [comment]
或者删除~/Library/Caches/CocoaPods目录下的search_index.json文件，重新pod search
