### ISSUE TITLE
iOS15上面无法设置导航栏透明

### ISSUE THREAD

**Issue by bigpig911** [QuintGao/GKNavigationBar#100]
if (@available(iOS 13.0, *)) {
        UINavigationBarAppearance *appearance = self.gk_navigationBar.standardAppearance;
        appearance.backgroundImage = image;
        appearance.backgroundColor = color;
        
我多加了这一行才能实现，问一下有没有更好的方法可以不改作者的代码的情况下实现
> [appearance configureWithTransparentBackground];

        self.gk_navigationBar.standardAppearance = appearance;
        self.gk_navigationBar.scrollEdgeAppearance = appearance;
    }

**Comment by QuintGao** [comment]
两种方案：
1、设置gk_navBarAlpha
```
self.gk_navBarAlpha = 0;
```
2、设置gk_navBackgroundColor
```
if (@available(iOS 13.0, *)) {
    [self.gk_navigationBar.standardAppearance configureWithTransparentBackground];
}
self.gk_navBackgroundColor = UIColor.clearColor;
```

**Comment by chenjc0317** [comment]
我设置了gk_navBackgroundColor = .clear 让导航栏变透明，升级了1.7.3之后有bug，1.7.2没事。
![image](https://user-images.githubusercontent.com/47734570/164132199-5fc0dcc5-a0f0-47fa-81b6-ceb266f1cd20.png)

**Comment by QuintGao** [comment]
最新版已修复
