### ISSUE TITLE
1.7.3导航栏变透明Bug

### ISSUE THREAD

**Issue by chenjc0317** [QuintGao/GKNavigationBar#101]
我设置了gk_navBackgroundColor = .clear 让导航栏变透明，升级了1.7.3之后有bug，1.7.2没事。
![image](https://user-images.githubusercontent.com/47734570/164132199-5fc0dcc5-a0f0-47fa-81b6-ceb266f1cd20.png)

**Comment by QuintGao** [comment]
#100
