### ISSUE TITLE
gk_navItemRightSpace   这一句不执行或者无意义

### ISSUE THREAD

**Issue by 295060456** [QuintGao/GKNavigationBar#103]
![image](https://user-images.githubusercontent.com/13795605/173317756-a6ae3bbc-02d4-4a13-9079-5579f30d3db0.png)
- (void)viewDidLoad {
    [super viewDidLoad];
    self.gk_navItemRightSpace = JobsWidth(16);/// 这一句不执行或者无意义
    self.gk_navRightBarButtonItems = @[[UIBarButtonItem.alloc initWithCustomView:self.ruleBtn]];
    self.categoryView.alpha = 1;
}

示例代码：https://github.com/295060456/JobsBaseConfig
![image](https://user-images.githubusercontent.com/13795605/173318139-27e3b367-74d2-46b4-a715-0b2f93ab0f90.png)
![image](https://user-images.githubusercontent.com/13795605/173318318-ccd8dbb5-8440-4498-8935-5e7cda8ae5af.png)
因为你是封装系统的，所以不管你怎么封装都是要落实到self.gk_navRightBarButtonItem.customView

我这里设置左右间距无效。示例代码在上面，你pod下来就可以看到。

**Comment by QuintGao** [comment]
![image](https://user-images.githubusercontent.com/13514024/173523907-984faa6f-fc47-4d90-900f-7e63d2377ff8.png)
把JXCategoryViewWithHeaderViewSubVC的导航栏相关代码去掉就好了，不需要导航栏的控制器不要调用相关方法

**Comment by 295060456** [comment]
> ![image](https://user-images.githubusercontent.com/13514024/173523907-984faa6f-fc47-4d90-900f-7e63d2377ff8.png) 把JXCategoryViewWithHeaderViewSubVC的导航栏相关代码去掉就好了，不需要导航栏的控制器不要调用相关方法

不需要GK_Navigation的不调用相关方法，其实现实开发办不到，因为你无法避免继承，很多UI是依据Bar.mas_Bottom来的
相当于就要在子类去父类调用相关代码以后，然后去相关具体的子类屏蔽GK_Navigation。这也就是为什么：
@interface JXCategoryViewWithHeaderViewVC : BaiShaETProjMembersSubsBaseVC的根本原因。

还有就是，我现在没这么写了，还是不行：
![image](https://user-images.githubusercontent.com/13795605/173724779-963bb099-096f-4d59-9cdb-33e6b2535da5.png)

**Comment by QuintGao** [comment]
最新版已修复
