### ISSUE TITLE
看图说话：期望暴露UINavigationBar的内部类，否则某些功能比较棘手

### ISSUE THREAD

**Issue by 295060456** [QuintGao/GKNavigationBar#104]
看图说话
![image](https://user-images.githubusercontent.com/13795605/173488275-259bcc7a-409d-43ef-9bc3-07877488f3a4.png)
@interface GKCustomNavigationBar : UINavigationBar
![image](https://user-images.githubusercontent.com/13795605/173488106-4bb8b112-245a-4e83-8bc0-64da6aacf83e.png)
你这个属性是自读的readonly，我没有办法进行介入，除非是我手动集成你的代码，放弃pod管理

**Comment by 295060456** [comment]
如果让我一定要兼顾pod管理，我是这么做的：
1、![image](https://user-images.githubusercontent.com/13795605/173491173-dd082b3c-8b09-4edb-9bec-f0d910ce7036.png)
2、![image](https://user-images.githubusercontent.com/13795605/173491281-c4cfe236-8728-493d-be45-34a2b2c1c43d.png)
3、![image](https://user-images.githubusercontent.com/13795605/173491374-5fb5f80d-e584-4327-a148-7d6e9c377966.png)
4、结合JXCategoryView：https://github.com/pujiaxin33/JXCategoryView去做一些事
主要就是上推才出现titleLab的文字
![image](https://user-images.githubusercontent.com/13795605/173491403-bc22b8a6-baae-4351-84e5-781bc70e4555.png)
5、但是不想动你的代码怎么办呢？
    5.1、自己把你的工程里面的GKCustomNavigationBar模块移植到我的工程里面，并取消你的pod相关联（编译先编译pod），一定要取消h和m文件的关联
![image](https://user-images.githubusercontent.com/13795605/173491693-4d3f372f-8e36-4619-b259-f03b6bd205eb.png)
    5.2、![image](https://user-images.githubusercontent.com/13795605/173492005-7942c7de-bc69-4aa9-9188-c315385abe3c.png)【关键一步：pod先于自己的代码编译，全局一个文件，对这个文件引用进行指定target】

**Comment by QuintGao** [comment]
这个不是通用功能，可以自己fork修改
