### ISSUE TITLE
返回按钮用button

### ISSUE THREAD

**Issue by 295060456** [QuintGao/GKNavigationBar#105]
self.gk_navLeftBarButtonItem = [UIBarButtonItem gk_itemWithImage:image target:self action:@selector(backItemClick:)];

期望直接暴露一个btn，让外界修改，这样也减少你的这个第三方的属性
![image](https://user-images.githubusercontent.com/13795605/174471666-512d6c99-bf42-44ce-a02f-8739649599cc.png)
![image](https://user-images.githubusercontent.com/13795605/174471682-b6013ae1-b8b7-4e83-a60e-936b55ea693a.png)

**Comment by QuintGao** [comment]
可以自己写个分类支持一下
