### ISSUE TITLE
页面返回导致 gk_navigationBar 在最上层

### ISSUE THREAD

**Issue by lieryang** [QuintGao/GKNavigationBar#109]
版本: 1.8.8
UIViewController+GKNavigationBar文件中的gk_viewWillAppear方法
83~86 行代码
`// 将自定义导航栏放置顶层
  if (self.gk_navigationBar && !self.gk_navigationBar.hidden) {
     [self.view bringSubviewToFront:self.gk_navigationBar];
}`

导致的问题
1.导航栏 push 出来一个 vc1, 存在一个gk_navigationBar
2.vc1 中按钮触发一个和屏幕一样大的(view 实现的)业务弹框A(此时弹框 A 在vc1页面的最上层, 当然也在gk_navigationBar的上层)
3.弹框 A 中一个按钮点击后 push 或者present 一个 vc2
4.vc2关闭后, 会走上面的代码导致, vc1 中的gk_navigationBar在弹框 A 上层了

**Comment by QuintGao** [comment]
在vc1的viewWillAppear里面把弹框A放到最上层就行了

**Comment by lieryang** [comment]
👌🏻, 我试一下

**Comment by lieryang** [comment]
用上面的方式解决没有问题! 感谢作者!!!
