### ISSUE TITLE
生产环境还没有办法使用，还存在很多问题

### ISSUE THREAD

**Issue by Calugram** [QuintGao/GKNavigationBar#11]
1.全屏返回手势需要优化
2.。。。
3.。。。

**Comment by QuintGao** [comment]
你好，我的demo有问题吗?

**Comment by Calugram** [comment]
缩放状态，滑动放回，并没有那么灵敏，而是手指要滑动一段距离后才会执行，和今日图条还是不一样的

**Comment by Calugram** [comment]
你的那个basenavigationcontroller也是有这个问题的，😄

**Comment by QuintGao** [comment]
缩放程度及偏移量可以自己设置的
