### ISSUE TITLE
TabbarController下vc的导航状态栏设置LightContent，显示一下黑色，才会显示白色

### ISSUE THREAD

**Issue by wyk190576528** [QuintGao/GKNavigationBar#12]
iOS 13系统及以上会出现上面问题，怎么修复

**Comment by QuintGao** [comment]
在控制器的init方法里设置gk_statusBarStyle

**Comment by wyk190576528** [comment]
@implementation BaseViewController
-(instancetype)init
{
    if ([super init])
    {
        self.gk_statusBarStyle = UIStatusBarStyleLightContent;//状态栏白色
    }
    return self;
}


修复无效，依旧是在初次显示页面时，先显示一下黑色，才会显示白色

**Comment by QuintGao** [comment]
我这里没问题啊，不知道你那是怎么导致的

**Comment by wyk190576528** [comment]
| |
王亚坤
|
|
wyk190576528@163.com
|
签名由网易邮箱大师定制


在2019年12月31日 15:03，QuintGao<notifications@github.com> 写道：

我这里没问题啊，不知道你那是怎么导致的

**Comment by wyk190576528** [comment]
看到视频中的演示了吗？这是运行的demo，只是tabbarController下的vc设置白色状态栏，就出现问题，13以上就会出现

**Comment by QuintGao** [comment]
没视频啊

**Comment by wyk190576528** [comment]
请查看邮件附件

**Comment by QuintGao** [comment]
没看到 你直接发我邮箱吧 1094887059@qq.com

**Comment by QuintGao** [comment]
我demo好像没问题啊，你下载最新版看下

**Comment by wyk190576528** [comment]
我下载的就是最新版demo啊，主要是demo中tabbarController中的vc状态栏设置的是StyleDefault，需要设置状态栏LightContent，就能复现问题了

**Comment by QuintGao** [comment]
最新版看下，网易云那个demo我把第三个设置为LightContent了。

**Comment by wyk190576528** [comment]
请查收邮件，还是有问题

**Comment by QuintGao** [comment]
问题已修复，请查看最新版本

**Comment by wyk190576528** [comment]
嗯嗯，能请教下，什么原因导致的呢？

**Comment by wyk190576528** [comment]
是没问题了，嵌套Navi导致
