### ISSUE TITLE
设置无效果

### ISSUE THREAD

**Issue by czpc** [QuintGao/GKNavigationBar#14]
按照这样的步骤。通过cocoapods 集成

1、在AppDelegate中添加导航配置
      [GKConfigure setupDefaultConfigure]
2、创建根导航控制器
      然后是tabbar 里设置的
     NSArray *vcs = @[vc1,vc2,vc3,vc4];
    NSMutableArray *viewControllers = [NSMutableArray arrayWithCapacity:0];
    [vcs enumerateObjectsUsingBlock:^(UIViewController *obj, NSUInteger idx, BOOL * _Nonnull stop) {
        UINavigationController *nav = [UINavigationController rootVC:obj];
        [viewControllers addObject:nav];
    }];
    self.viewControllers = viewControllers;
3、设置导航栏属性（调用即创建）
  self.gk_statusBarHidden = YES;
        self.gk_navLineHidden = NO;这些设置都无效

**Comment by QuintGao** [comment]
gk_statusBarHidden 这个确实无效，目前没找到解决办法，下面那个是有效的啊

**Comment by czpc** [comment]
我按照这样的方式集成的。看你的demo 都可以。但是我集成后就不行了。有没有群嘛。我可以录制视频给你看看

**Comment by QuintGao** [comment]
加我QQ吧  1094887059@qq.com
