### ISSUE TITLE
设置self.gk_navItemLeftSpace作用于所有navigationBar吗？

### ISSUE THREAD

**Issue by wyk190576528** [QuintGao/GKNavigationBar#15]
appdelegage中配置[GKConfigure setupCustomConfigure:gk_navItemLeftSpace为10，之后再控制器中单独设置gk_navItemLeftSpace为20，push下一页面后，gk_navItemLeftSpace还是20，所以，想问一下，gk_navItemLeftSpace属性是作用于所有navigationBar吗？

**Comment by QuintGao** [comment]
你好，这是个bug，最新版已修复

**Comment by wyk190576528** [comment]
我使用最新版，还是存在这个问题

**Comment by QuintGao** [comment]
0.0.6吗

**Comment by wyk190576528** [comment]
对

**Comment by QuintGao** [comment]
你把gk_navItemLeftSpace=20; 放到创建导航栏后面调用

**Comment by wyk190576528** [comment]
先后还有顺序？我都是在didload里设置naviBar的

**Comment by QuintGao** [comment]
对 你把这一句放到最后

**Comment by wyk190576528** [comment]
还是存在，push到第二个页面，没问题，距离是10，继续push到下一个页面，距离又变成20了

**Comment by QuintGao** [comment]
你好，我又更新了一版，你再试试

**Comment by wyk190576528** [comment]
试了下，没问题，👍👍👍
