### ISSUE TITLE
影响原有的导航

### ISSUE THREAD

**Issue by gyyxiaogao** [QuintGao/GKNavigationBar#16]
引入之后,不做任何操作,影响其他的导航显示,自动向左右偏移
![图片](https://user-images.githubusercontent.com/16957066/72702033-40fcf000-3b8c-11ea-8101-c0a84764102b.png)

**Comment by gyyxiaogao** [comment]
![图片](https://user-images.githubusercontent.com/16957066/72702066-596d0a80-3b8c-11ea-8fb8-f2e00356777e.png)

**Comment by QuintGao** [comment]
是的，默认不禁止间距调整，可以把gk_disableFixSpace设置为YES来禁止间距调整

**Comment by gyyxiaogao** [comment]
最新版本1.6.1又出现这个问题了，在iOS15.2（其他版本没有运行过）又出现了，设置YES也没用。

**Comment by QuintGao** [comment]
修复了  试试最新版
