### ISSUE TITLE
监听pop返回操作，手势返回怎么处理？

### ISSUE THREAD

**Issue by wyk190576528** [QuintGao/GKNavigationBar#17]
返回按钮点击事件有看到- (void)backItemClick:(id)sender;但手势返回的监听需要设置什么？

**Comment by QuintGao** [comment]
目前没有方法，我看看加一下

**Comment by wyk190576528** [comment]
viewControllerPopScrollBegan这个方法我可以监听到滑动返回操作，如果我再右滑返回，在这个方法中，做完本地数据处理后，手指还没有抬起，能再立即恢复原来滑动返回吗？

**Comment by QuintGao** [comment]
这个目前不能的
