### ISSUE TITLE
iOS13.3 升级13.4，出现个问题，在13.4上运行时状态栏状态错误

### ISSUE THREAD

**Issue by wyk190576528** [QuintGao/GKNavigationBar#19]
正常显示是白色，
![Jietu20200328-113444](https://user-images.githubusercontent.com/13128838/77814024-65bf9780-70e8-11ea-952f-4ea59b456e6c.jpg)
但是在13.4上，运行项目真机调试，APP启动，先显示白色，后又自动变成黑色；退出调试，启动APP，就没问题，一直显示白色，不会自动变黑
![Jietu20200328-114428](https://user-images.githubusercontent.com/13128838/77814161-7fadaa00-70e9-11ea-9952-f2f72ff86ea4.jpg)

**Comment by QuintGao** [comment]
确实有这个问题，测试发现iOS13.4在调试的时候分类中的下面两个方法不执行，目前能想到的解决办法是在基类控制器中，实现下面两个方法
```
- (BOOL)prefersStatusBarHidden {
    return self.gk_statusBarHidden;
}

- (UIStatusBarStyle)preferredStatusBarStyle {
    return self.gk_statusBarStyle;
}

**Comment by wyk190576528** [comment]
![Jietu20200328-131524](https://user-images.githubusercontent.com/13128838/77815459-34e65f00-70f6-11ea-8176-17268e4879ff.jpg)
基类添加这两个方法后，启动后，切换其他tabbar会出现
