### ISSUE TITLE
你好。有没有swift的demo呢？

### ISSUE THREAD

**Issue by guobin510** [QuintGao/GKNavigationBar#2]
你好。我这边使用swift A页面push到B页面，B页面返回的时候，A页面的导航栏就消失了，内容也会向上缩进

**Comment by QuintGao** [comment]
我这没问题啊

**Comment by guobin510** [comment]
你好。是我自己的问题。我已经解决了。我之前使用的是系统的rootViewController方法，后面改成 GKNavigationBar 的 rootVC 方法问题就解决了。谢谢你。
系统的方法
      let child = BaseNavigation Controller(rootViewController: type.init())
GKNavigationBar 的方法
      let child = BaseNavigationController.rootVC(type.init())

**Comment by guobin510** [comment]
是我自己的问题，我已经解决了，我导航栏添加的时候使用的是系统的rootview方法，后面改成GKNavigationBar的rootVC方法就好了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: QuintGao <notifications@github.com&gt;
发送时间: 2019年11月9日 23:33
收件人: QuintGao/GKNavigationBar <GKNavigationBar@noreply.github.com&gt;
抄送: guobin510 <guobin5@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[QuintGao/GKNavigationBar] 你好。有没有swift的demo呢？ (#2)




我这没问题啊
