### ISSUE TITLE
状态栏设置无效

### ISSUE THREAD

**Issue by RichardDuan** [QuintGao/GKNavigationBar#22]
self.gk_statusBarStyle = UIStatusBarStyleLightContent;
viewDidLoad当中设置无效

**Comment by QuintGao** [comment]
2、Xcode 11.4 在调试的时候会出现状态栏样式改变不了的情况 解决办法：在基类控制器里实现下面两个方法

- (BOOL)prefersStatusBarHidden {
    return self.gk_statusBarHidden;
}

- (UIStatusBarStyle)preferredStatusBarStyle {
    return self.gk_statusBarStyle;
}
