### ISSUE TITLE
设置配置问题

### ISSUE THREAD

**Issue by ZClee128** [QuintGao/GKNavigationBar#25]
// 配置导航栏属性
    [GKConfigure setupCustomConfigure:^(GKNavigationBarConfigure * _Nonnull configure) {
        configure.gk_translationX = 15;
        configure.gk_translationY = 20;
        configure.gk_scaleX = 0.90;
        configure.gk_scaleY = 0.92;
        // 导航栏背景色
        configure.backgroundColor = [UIColor whiteColor];
        // 导航栏标题颜色
        configure.titleColor = tabbarBlackColor;
        // 导航栏标题字体
        configure.titleFont = MedFont17;
        // 导航栏返回按钮样式
        configure.backStyle = GKNavigationBarBackStyleBlack;
        // 导航栏左右item间距
        configure.gk_navItemLeftSpace = WidthOfScale(8.5);
        configure.gk_navItemRightSpace = 12.0f;
    }];
这个设置完并没有生效
<img width="599" alt="图片" src="https://user-images.githubusercontent.com/18162711/88001021-aa58be00-cb31-11ea-8f08-2fc79d72a8b2.png">
你的源码内部直接调用默认配置，这个有问题吧

**Comment by QuintGao** [comment]
控制器中你怎么使用的？
