### ISSUE TITLE
右滑返回的手势与别的三方冲突

### ISSUE THREAD

**Issue by wyk190576528** [QuintGao/GKNavigationBar#27]
[page_demo.zip](https://github.com/QuintGao/GKNavigationBar/files/4951978/page_demo.zip)
示例demo如上

**Comment by QuintGao** [comment]
[page_demo 2.zip](https://github.com/QuintGao/GKNavigationBar/files/4952331/page_demo.2.zip)
修改了下库和demo，看看是不是你要的效果

**Comment by wyk190576528** [comment]
解压后没有GKNavigationBar文件，这个有修改吗？

**Comment by QuintGao** [comment]
可能我没替换好，你重新从git上下载一份吧，有修改

**Comment by wyk190576528** [comment]
👍
