### ISSUE TITLE
大神问下。。我只想用像抖音那种左滑push、pop的功能。。 需要引入那些文件？

### ISSUE THREAD

**Issue by liubang0909** [QuintGao/GKNavigationBar#28]
可以不设置导航栏吗？自己封装的有。。

**Comment by QuintGao** [comment]
可以的，只要不调用导航栏相关的方法就行

**Comment by liubang0909** [comment]
大神能不能指点下。。都需要引入哪些文件。。我比较菜。。

**Comment by liubang0909** [comment]
有那种只引入分类就可以实现的就好了。。

**Comment by QuintGao** [comment]
应该需要全部导入，然后在对应的控制器中设置self.gk_pushDelegate = self，然后实现对应的代理方法就行了

**Comment by liubang0909** [comment]
大神我刚试了下 引入#import "GKCategory.h"
 设置
self.navigationController.gk_openScrollLeftPush = YES;
self.gk_pushDelegate=self;
- (void)pushToNextViewController{  
    [self.navigationController pushViewController:[ViewController new] animated:YES];
}

代理方法没触发。。该怎么调试下。。

**Comment by QuintGao** [comment]
UINavigationController的初始化方法需要改成+ (instancetype)rootVC:(UIViewController *)rootVC; 这个方法

**Comment by liubang0909** [comment]
好的👌  谢谢大佬回复！已经star  谢谢🙏

**Comment by liubang0909** [comment]
有个怪现象啊。。刚开始启动进来不起作用。。  我切换了tabbar回来就起作用了。。

**Comment by liubang0909** [comment]
gk_openScrollLeftPush 这个属性设置的时机有讲究吗？ 我看了下-(void)viewWillAppear:(BOOL)animated    -(void)viewWillDisappear:(BOOL)animated  都没有写什么特殊的代码。。有种页面消失再回来才打开了开关的感觉

**Comment by liubang0909** [comment]
+ (void)load {
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        NSArray <NSString *> *oriSels = @[@"viewDidLoad",
                                          @"viewWillAppear:",
                                          @"viewDidAppear:",
                                          @"viewWillLayoutSubviews"];
        
        [oriSels enumerateObjectsUsingBlock:^(NSString * _Nonnull oriSel, NSUInteger idx, BOOL * _Nonnull stop) {
            gk_swizzled_instanceMethod(self, oriSel, self);
        }];
    });
}
确实是有方法交换。。 大神帮忙分析下是啥原因。。该怎么调下

**Comment by liubang0909** [comment]
都在发送这个通知 GKViewControllerPropertyChangedNotification  然后 都能走到            [self.panGesture addTarget:self.navigationHandler action:@selector(panGestureAction:)];  刚开始的手势方法不起作用  切换了tabbar之后  手势方法触发了

**Comment by QuintGao** [comment]
确实有点问题，我又更新了一版，你下载下来再试试

**Comment by liubang0909** [comment]
可以了。。  大神我看了下代码修改的地方。。  有空的话能说下是啥原因就好了。。

**Comment by liubang0909** [comment]
我对GitHub了解得比较少。。 下载的代码和pod的有可能不一致是吗？ pod的每次都需要单独的更新？

**Comment by QuintGao** [comment]
原因是以前对根控制器手势的添加做了处理，最新版去掉了，且增加了对非本导航控制器的屏蔽
最新版1.1.1  pod已更新

**Comment by liubang0909** [comment]
好的 大神辛苦了！ 感谢🙏。已加入pod管理
