### ISSUE TITLE
为何项目中直接替换新版GKNavigationbar,运行报错啊

### ISSUE THREAD

**Issue by wyk190576528** [QuintGao/GKNavigationBar#29]
![Jietu20200723-093147](https://user-images.githubusercontent.com/13128838/88244912-d0b06200-ccc7-11ea-896e-3e413771b695.jpg)

**Comment by QuintGao** [comment]
是用pod还是直接拖入项目的，怎么使用的？

**Comment by wyk190576528** [comment]
直接拖入的，可以用pod吗？没看到有说明啊

**Comment by QuintGao** [comment]
可以用pod，最上面有版本号，说明上没写

**Comment by wyk190576528** [comment]
嗯，我先改用pod试试

**Comment by wyk190576528** [comment]
改用pod更新，没问题
