### ISSUE TITLE
如果使用xib布局的，是不是都要单独把top值修改下呢？

### ISSUE THREAD

**Issue by guobin510** [QuintGao/GKNavigationBar#3]
如果使用xib布局的，是不是都要单独把top值修改下呢？
例如：layoutScrollViewCons.constant = navigationHeight  （改成gk_navigationBar的下面）

**Comment by QuintGao** [comment]
是的，由于系统导航栏被隐藏了，所以跟系统导航相关的方法都失效了。

**Comment by guobin510** [comment]
好的。我已经明白了。谢谢
