### ISSUE TITLE
gk_backImage设置问题

### ISSUE THREAD

**Issue by wyk190576528** [QuintGao/GKNavigationBar#30]
appdelegate设置
[GKConfigure setupCustomConfigure:{
configure.backImage = ImgName(@"btn_back_black");//设置返回按钮图片
}
push的下个页面，如果无返回按钮的话，怎么设置呢？

**Comment by QuintGao** [comment]
可以设置gk_navLeftBarButtonItem = nil

**Comment by wyk190576528** [comment]
👍
