### ISSUE TITLE
使用TZImagePickerController闪退

### ISSUE THREAD

**Issue by jianjianhao** [QuintGao/GKNavigationBar#32]
<img width="1400" alt="252A6A7354C9C223A9F6D7EF66E53E49" src="https://user-images.githubusercontent.com/12797357/88376543-325bf380-cdd0-11ea-8d0a-a32697a30ec3.png">
[TZImagePickerController-master.zip](https://github.com/QuintGao/GKNavigationBar/files/4971075/TZImagePickerController-master.zip)
不知道是不是冲突了

**Comment by QuintGao** [comment]
交换方法导致的循环调用问题，最新版已修复
