### ISSUE TITLE
configure.titleColor有种情况会无效

### ISSUE THREAD

**Issue by wyk190576528** [QuintGao/GKNavigationBar#33]
有设置configure.titleColor = [UIColor redColor];
在VC中
- (void)viewDidLoad {
    [super viewDidLoad];
    
    self.view.backgroundColor = [UIColor whiteColor];
    self.gk_navigationItem.title = @"MainVC";
//    self.gk_navBackgroundColor = [UIColor redColor];
//    self.gk_statusBarStyle = UIStatusBarStyleLightContent;
//    self.gk_navTitleFont = [UIFont systemFontOfSize:18.0f];
//    self.gk_navTitleColor = [UIColor whiteColor];
}

此时标题颜色不是redColor，还是黑色的

**Comment by QuintGao** [comment]
最新版已修复
