### ISSUE TITLE
经过测试KSYMediaPlayback 的 prepareToPlay会影响禁止侧滑（我自己打断点看源码已经解决，望作者采纳）

### ISSUE THREAD

**Issue by 295060456** [QuintGao/GKNavigationBar#34]
- (void)viewDidLoad {
    [super viewDidLoad];
    self.gk_interactivePopDisabled = YES;
    self.gk_fullScreenPopDisabled = YES;
    WeakSelf
    [self requestAdBlock:^(id data) {
        if ((Boolean)data) {

            [weakSelf addPlayVideo];
            [weakSelf dataGet];

        }else{

            [weakSelf.navigationController popViewControllerAnimated:YES];

        }

    }];
//
    [self addNotifi];
}

在SceneDelegate.m
-(UINavigationController *)navigationController{
    if (!_navigationController) {
//        _navigationController = [[UINavigationController alloc] initWithRootViewController:self.customSYSUITabBarController];
        _navigationController = [UINavigationController rootVC:self.customSYSUITabBarController
                                               transitionScale:NO];
        _navigationController.navigationBar.hidden = YES;
    }return _navigationController;
}

 [self.mkPlayVideo.mkPlayer prepareToPlay];在addPlayVideo里面，目前解决方案还在研讨中ing

https://www.jianshu.com/p/4a569fd64c93用这种方法可以实现效果 但是为什么不走GK的我还在想...

解决方案：

1、在 - (void)propertyChangeNotification:(NSNotification *)notification 里面的 if (vc.gk_interactivePopDisabled）分支：
更改为：
        if ([self respondsToSelector:@selector(interactivePopGestureRecognizer)]) {
            //这里对添加到右滑视图上的所有手势禁用
            for (UIGestureRecognizer *popGesture in self.interactivePopGestureRecognizer.view.gestureRecognizers) {
                popGesture.enabled = NO;
            }
        }
        self.interactivePopGestureRecognizer.delegate = nil;
        self.interactivePopGestureRecognizer.enabled = NO;
        [self.interactivePopGestureRecognizer.view removeGestureRecognizer:self.screenPanGesture];
        [self.interactivePopGestureRecognizer.view removeGestureRecognizer:self.panGesture];

2、在 - (instancetype)initWithRootVC:(UIViewController *)rootVC transitionScale:(BOOL)transitionScale 里面添加：
self.interactivePopGestureRecognizer.delegate = self.gestureHandler;

遗憾：
 禁止全屏滑动，支持边缘滑动 这里面怎么写 没时间研究了
其他地方涵盖以及兼容问题没看

**Comment by QuintGao** [comment]
我试了下 并没有发现会影响，可否提供demo我试下

**Comment by 295060456** [comment]
可以 ，最近几天比较忙，等我缓缓。
