### ISSUE TITLE
还有个问题

### ISSUE THREAD

**Issue by 295060456** [QuintGao/GKNavigationBar#35]
在 @implementation GKBaseAnimatedTransition

这么写
+ (instancetype)transitionWithScale:(BOOL)isScale {
    return [[GKBaseAnimatedTransition alloc] initWithScale:isScale];
}

否则 我手动拖你的项目到我的项目里面编译不通过，因为Multiple methods named 'initWithScale:' found with mismatched result, parameter type or attributes
全局搜索 发现是和 YYKit 里面的 YYImageCoder 的initWithScale 冲突 
改正以后编译通过。

**Comment by QuintGao** [comment]
最新版已修改
