### ISSUE TITLE
cocopods problems

### ISSUE THREAD

**Issue by 295060456** [QuintGao/GKNavigationBar#36]
[!] CocoaPods could not find compatible versions for pod "GKNavigationBar":
  In Podfile:
    GKNavigationBar (~> 1.1.3)

None of your spec sources contain a spec satisfying the dependency: `GKNavigationBar (~> 1.1.3)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Comment by QuintGao** [comment]
用pod update试试
