### ISSUE TITLE
swift版本目前问题比较多，然后导入这个OC版本，按照demo设置后发现侧滑手势始终不起效了

### ISSUE THREAD

**Issue by dulifu** [QuintGao/GKNavigationBar#37]
<img width="744" alt="截屏2020-08-04 下午11 52 20" src="https://user-images.githubusercontent.com/17981102/89315904-f8cb9800-d6ad-11ea-9042-fa3b16e3c442.png">
<img width="771" alt="截屏2020-08-04 下午11 53 43" src="https://user-images.githubusercontent.com/17981102/89315909-f9fcc500-d6ad-11ea-9a7a-eea2fe230ad3.png">

**Comment by QuintGao** [comment]
1、Swift版本有什么问题？我这使用正常啊
2、要开启侧滑手势需要将UINavigationController的初始化方法改成+ (instancetype)rootVC:(UIViewController *)rootVC这个

**Comment by dulifu** [comment]
了解了  好像没有暂时没问题了，谢谢
