### ISSUE TITLE
导航栏左右按钮设置的间距，有时候会失效

### ISSUE THREAD

**Issue by lxm1799** [QuintGao/GKNavigationBar#38]
在第一级界面设置好导航栏按钮间距，进入到子界面时候，再次返回会导致导航栏间距失效。

目前确定会发生的条件：在第一级界面设置按钮间距，进入图片预览（使用的是TZImagePreviewController预览功能），关闭预览功能之后，导航栏按钮间距失效。

**Comment by QuintGao** [comment]
我这边测试没发现问题，可否提供demo，或者在我的demo上能否复现？

**Comment by lxm1799** [comment]
好的，晚点提供demo




| |
博览己用
|
|
邮箱：goodlucky1130@163.com
|

签名由 网易邮箱大师 定制

在2020年08月10日 14:56，QuintGao 写道：

我这边测试没发现问题，可否提供demo，或者在我的demo上能否复现？

**Comment by lxm1799** [comment]
这两天我按照项目里面过程写了一个demo，发现这个问题无法复现了。
另外项目之前确实存在这个bug，后来自己自定义了这个导航栏实现了。


| |
博览己用
|
|
邮箱：goodlucky1130@163.com
|

签名由 网易邮箱大师 定制

在2020年08月10日 14:56，QuintGao 写道：

我这边测试没发现问题，可否提供demo，或者在我的demo上能否复现？

**Comment by sdwangxianwen** [comment]
我也遇到了，如果没有对TZImagePickerController进行处理，默认的present的话会造成失效，但是如果设置imagePickerVc?.modalPresentationStyle = .fullScreen的话就没有问题

**Comment by QuintGao** [comment]
可以试试最新版
