### ISSUE TITLE
ios13下，设置gk_navItemLeftSpace属性无效

### ISSUE THREAD

**Issue by Surrel** [QuintGao/GKNavigationBar#4]
- 调试发现
- (void)setGk_navLeftBarButtonItem:(UIBarButtonItem *)gk_navLeftBarButtonItem {
    objc_setAssociatedObject(self, &kAssociatedObjectKey_navLeftBarButtonItem, gk_navLeftBarButtonItem, OBJC_ASSOCIATION_RETAIN_NONATOMIC);
    
    self.gk_navigationItem.leftBarButtonItem = gk_navLeftBarButtonItem;
}
ios13下，程序走到这里就结束了，不进里面调整间距的代码

**Comment by Surrel** [comment]
又测试了下，ios13首次显示这页面的时候间距没有生效，之后切换tabbar又到这页面后，生效了

**Comment by QuintGao** [comment]
问题已修复，请使用最新版。

**Comment by Surrel** [comment]
谢谢大佬，我这边显示正常了

**Comment by F80EZ6** [comment]
大佬威武555  效率真快     @QuintGao
