### ISSUE TITLE
添加子视图，导航栏被遮盖了

### ISSUE THREAD

**Issue by wyk190576528** [QuintGao/GKNavigationBar#40]
下面有操作演示和demo

![Jietu20200901-145024](https://user-images.githubusercontent.com/13128838/91811723-89bc7180-ec62-11ea-92ab-1a19a1ef33f5.gif)
[page_demo.zip](https://github.com/QuintGao/GKNavigationBar/files/5154403/page_demo.zip)

**Comment by QuintGao** [comment]
子视图需要添加到导航栏下方

**Comment by wyk190576528** [comment]
在某些封装库里，不能判断当前父视图是不是带有导航栏，所以添加子视图，有时会添加在导航栏下面

**Comment by wyk190576528** [comment]
添加子视图事件，如果发生在vc的viewDidLoad中，子视图就不会覆盖导航栏

**Comment by QuintGao** [comment]
你新添加的把导航栏盖住了，可以调用bringSubviewToFront把导航栏放到最上面，或者就设置子视图的y值在导航栏下方

**Comment by wyk190576528** [comment]
有别的方案吗？

**Comment by QuintGao** [comment]
没 目前只能这样

**Comment by yinjining** [comment]
- (void)hk_viewDidLayoutSubviews {
    [self hk_viewDidLayoutSubviews];
    if (self.gk_NavBarInit && self.gk_navigationBar && !self.gk_navigationBar.hidden) {
        [self.view bringSubviewToFront:self.gk_navigationBar];
    }
}

用这个方案更友好。写load方法交换 viewDidLayoutSubviews 与  hk_viewDidLayoutSubviews
