### ISSUE TITLE
Class GKPopAnimatedTransition is implemented in both xxxx One of the two will be used.Which one is undefined

### ISSUE THREAD

**Issue by hansong8675** [QuintGao/GKNavigationBar#41]
Class GKPopAnimatedTransition is implemented in both /private/var/containers/Bundle/Application/xxx/Frameworks/GKNavigationBar.framework/GKNavigationBar (0x10257c778) and /private/var/containers/Bundle/Application/xxx/xxx.app/xxx (0x1013d3d28). One of the two will be used. Which one is undefined.

**Comment by QuintGao** [comment]
命名冲突了？
