### ISSUE TITLE
实现抖音的左滑push功能时，如果手势取消了，仍然会push，想问下是否需要通过修改GKPushAnimatedTransition来解决

### ISSUE THREAD

**Issue by MrBugDou** [QuintGao/GKNavigationBar#43]

**Comment by QuintGao** [comment]
可以通过调整gk_pushTransitionCriticalValue来处理

**Comment by MrBugDou** [comment]
![image](https://user-images.githubusercontent.com/12947653/92870371-5e8e0b00-f436-11ea-97be-bb428093797e.png)
您看，我没有改现在还是默认值0.3，只拖出来一点点（模拟器不好操作，真机上拖更少也一下），但是一松手还是会push
pushdelegate代码如下
![image](https://user-images.githubusercontent.com/12947653/92870687-b4fb4980-f436-11ea-9bea-c2def681c27d.png)

**Comment by MrBugDou** [comment]
![image](https://user-images.githubusercontent.com/12947653/92870839-dc521680-f436-11ea-9fcf-1c313519cac5.gif)

**Comment by MrBugDou** [comment]
![Untitled](https://user-images.githubusercontent.com/12947653/92870898-ec69f600-f436-11ea-8379-ce9fe5ac7eaf.gif)

**Comment by MrBugDou** [comment]
我刚下载了Demo，demo是没问题的，希望您帮助我排查一下问题，谢谢

**Comment by QuintGao** [comment]
我这调试没问题，可否提供demo我试一下

**Comment by MrBugDou** [comment]
抱歉，是我的问题，我没有初始化GKNavigationBarConfigure，初始化GKNavigationBarConfigure之后没问题了，谢谢您

**Comment by QuintGao** [comment]
好的
