### ISSUE TITLE
侧滑不行

### ISSUE THREAD

**Issue by 295060456** [QuintGao/GKNavigationBar#44]
https://github.com/295060456/JobsSearch

因为这个东西我最近还在写，你拉代码的时机我没法掌控，简单做以下说明：
1、如果启用FDFullscreenPopGesture 文件夹下的两个类 UINavigationController+FDFullscreenPopGesture 和 UIScrollView+FDFullscreenPopGesture（在target membership里面打钩包含资源文件进编译树，就是Xcode右侧的侧边栏那边）
没毛病

但是我想你既然写了这个，我就用你的，那么1不打勾不包含的情况下，在@implementation JobsSearchVC 里面的viewDidLoad实现了以下代码：
        self.isBackBtnBlackorWhite = YES;
        self.gk_navLeftBarButtonItem = [[UIBarButtonItem alloc] initWithCustomView:self.backBtnCategory];
        self.gk_navRightBarButtonItem = [[UIBarButtonItem alloc] initWithCustomView:self.scanBtn];
        self.gk_navBackgroundColor = self.bgColour;
//        self.gk_captureImage;
        self.gk_interactivePopDisabled = NO;
        self.gk_fullScreenPopDisabled = NO;
        
        self.gk_navTitle = self.titleStr;
        [self hideNavLine];
        [self.view bringSubviewToFront:self.gk_navigationBar];
        self.gk_navigationBarHeight = self.gk_navigationBar.mj_h;

执行失败！！！！

我害怕其他变量进行了影响，为了环境的纯洁，我在其他控制器（ViewController_2 ——> ViewController_3）里面作如下操作同样失败；
ViewController_3 代码如下：
    self.gk_navTitle = @"Demo";
    self.gk_navTitleColor = [UIColor whiteColor];
    self.gk_navBackgroundColor = [UIColor redColor];
    self.gk_navShadowColor = [UIColor blackColor];
    self.gk_backStyle = GKNavigationBarBackStyleWhite;
    self.gk_navItemRightSpace = 0;
    
    self.gk_interactivePopDisabled = NO;
    self.gk_fullScreenPopDisabled = NO;

**Comment by QuintGao** [comment]
我这个与FDFullscreenPopGesture不能混用

**Comment by 295060456** [comment]
我想代码里面就不要相似模块多了不好管理怕冲突，你那个怎么用？如果可以用就用你的，我就舍弃FDFullscreenPopGesture

**Comment by QuintGao** [comment]
按照demo使用就行
