### ISSUE TITLE
报错信息:  'sharedApplication' is unavailable: not available on iOS (App Extension) -

### ISSUE THREAD

**Issue by wangergang** [QuintGao/GKNavigationBar#46]
报错信息如下:
'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.

设置 Require Onlu App-Extension-Safe API  为 YES  仍然报错的

**Comment by QuintGao** [comment]
这个是怎么出现的，我demo有这个问题吗？
