### ISSUE TITLE
建议右滑内容返回独立出去，不要放到导航栏这个框架内，因为这可能和原有工程的右滑内容返回冲突

### ISSUE THREAD

**Issue by uldh** [QuintGao/GKNavigationBar#49]
我原有工程的右滑返回要处理的情况很复杂，引入本框架后，影响了原有功能

**Comment by QuintGao** [comment]
使用系统方法创建导航控制器，不会影响侧滑

**Comment by QuintGao** [comment]
最新版1.3.0 已区分不同模块，可使用pod 'GKNavigationBar/NavigationBar' 导入导航栏模块
