### ISSUE TITLE
发现一个页面卡死的问题

### ISSUE THREAD

**Issue by kevinszjmm** [QuintGao/GKNavigationBar#53]
复现流程：
VC(A)  push to VC(B) push to VC(C)
VC(B)设置 self.gk_fullScreenPopDisabled = YES;
当 VC(C)触发手势返回的时候，页面卡死
看了一下页面结构，其实VC(C)这时候已经不存在了

**Comment by QuintGao** [comment]
我demo能复现吗，我没试出来

**Comment by kevinszjmm** [comment]
可以复现的：
GKWYNewsDetailViewController.m  viewDidLoad中设置self.gk_interactivePopDisabled = YES;
从GKWYNewsDetailViewController  push到GKWYNewsCommentViewController中， GKWYNewsCommentViewController手势返回的时候，会出现问题

**Comment by kevinszjmm** [comment]
> 我demo能复现吗，我没试出来

在viewDidAppear里设置self.gk_interactivePopDisabled = YES
在viewDidDisappear里设置self.gk_interactivePopDisabled = NO
是ok的
