### ISSUE TITLE
全局返回手势问题

### ISSUE THREAD

**Issue by wangchaoya** [QuintGao/GKNavigationBar#55]
if (transition.x < 0) { // 左滑
        // 开启了左滑push并设置了代理
        if (self.navigationController.gk_openScrollLeftPush && visibleVC.gk_pushDelegate) {
            [gestureRecognizer removeTarget:self.systemTarget action:self.systemAction];
        }else {
            return NO;
        }
    }

这里 有可能是=0 且是左滑的情况
比如在一个不可滑动的页面右下角做左下滑动，则设置的距离没用 改成 <=0 后达到预期

**Comment by QuintGao** [comment]
没太明白，具体是什么效果？

**Comment by wangchaoya** [comment]
可能是多个框架共同作用引起的
