### ISSUE TITLE
wkwebview 侧滑手势冲突

### ISSUE THREAD

**Issue by wangchaoya** [QuintGao/GKNavigationBar#57]
大佬可以增加一个和wkwebview 侧滑手势冲突的分类吗
allowsBackForwardNavigationGestures 这个属性开启后，如果wkwebview 可以返回上一页则，禁止侧滑返回，如果是首页则侧滑返回

类似这种
if (webView.allowsBackForwardNavigationGestures == YES && webView.canGoBack == YES) {
        return false;
    }

**Comment by QuintGao** [comment]
这个用分类的话不太好，我写了使用的demo，可以参考

**Comment by wangchaoya** [comment]
看到了
