### ISSUE TITLE
ld: symbol(s) not found for architecture arm64 报错

### ISSUE THREAD

**Issue by AutumnBulu** [QuintGao/GKNavigationBar#58]
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_GKGestureHandleConfigure", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_GKNavigationBarConfigure", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Xcode 版本：12.3
pod install 方式
iOS 版本：12.4.9

**Comment by QuintGao** [comment]
哪个版本，新建项目也是这样吗

**Comment by AutumnBulu** [comment]
pod 'GKNavigationBar', '~> 1.3.7'

**Comment by AutumnBulu** [comment]
最新版本，项目也是刚建的

**Comment by QuintGao** [comment]
我试了没问题的啊

**Comment by AutumnBulu** [comment]
嗯嗯，好的，应该是我这边的问题，
