### ISSUE TITLE
状态栏文字样式修改问题

### ISSUE THREAD

**Issue by AutumnBulu** [QuintGao/GKNavigationBar#59]
按钮描述已添加 init 视图初始化的方式定义：self.gk_statusBarStyle = UIStatusBarStyleDefault; 基类已经重写：- (BOOL)prefersStatusBarHidden {
    return self.gk_statusBarHidden;
}

- (UIStatusBarStyle)preferredStatusBarStyle {
    return self.gk_statusBarStyle;
}的方法，并且已验证方法已执行，可还是无法修改状态栏文字样式，请问还需要额外配置什么文件吗？（自定义的 UINavigationViewController中也按照demo的设计，添加了：- (UIViewController *)childViewControllerForStatusBarHidden {
    return self.topViewController;
}

- (UIViewController *)childViewControllerForStatusBarStyle {
    return self.topViewController;
}
）

**Comment by QuintGao** [comment]
具体的导航结构是什么样的，我demo可以复现吗

**Comment by AutumnBulu** [comment]
你好方便添加一下我的微信吗？切图添加后好像无法查看。我的微信：Chausang_1004  。另外demo中无法复现，是正常的可手动改变状态栏样式的。
