### ISSUE TITLE
导航栏高度不兼容ipad

### ISSUE THREAD

**Issue by wyk190576528** [QuintGao/GKNavigationBar#62]
// 导航栏高度
#define GK_NAVBAR_HEIGHT            44.0f
建议修改宏定义为
#define GK_NAVBAR_HEIGHT \
^(){\
if (@available(iOS 12.0, *)) {\
    return GK_IS_iPad?50.f:44.f;\
} else {\
    return 44.f;\
}\
}()

**Comment by QuintGao** [comment]
最新版已优化
