### ISSUE TITLE
Xcode调试切换深色模式和正常模式 当前导航栏颜色不切换

### ISSUE THREAD

**Issue by nicetime-free** [QuintGao/GKNavigationBar#64]
### 这里是我设置动态颜色的方法

[```
GKConfigure setupCustomConfigure:^(GKNavigationBarConfigure * _Nonnull configure) {
        configure.backgroundColor = PGNavBgColor;
        configure.titleColor = PGNavTitleColor;
        configure.titleFont = PGNavTitleFont;
        configure.lineColor = PGNavLineColor;
    }];
```
```
+ (UIColor *)pgDynamicColor: (UIColor *)lightColor darkColor: (UIColor *)darkColor {
    
    if (@available(iOS 13.0, *)) {
        UIColor *dyColor;
        dyColor = [UIColor colorWithDynamicProvider:^UIColor * _Nonnull(UITraitCollection * _Nonnull trainCollection) {
            if ([trainCollection userInterfaceStyle] == UIUserInterfaceStyleLight) {
                return lightColor;
            }else {
                return darkColor;
            }
        }];
       return dyColor;
    }
    return lightColor;
}
```

动态颜色设置应该没问题 控制器背景颜色跟随主题切换了

**Comment by QuintGao** [comment]
导航栏背景色内部是通过设置BackgroundImage来修改背景的，所以不支持动态颜色，只能通过监听traitCollectionDidChange方法来自己修改背景色。

**Comment by QuintGao** [comment]
最新版1.4.1内部对模式切换做了处理，可以支持动态颜色
