### ISSUE TITLE
从系统导航栏返回键点击切换到自定义导航栏首页时，可以明显看到顶部白色导航栏消失的效果，不太友好，请问这个可以优化吗

### ISSUE THREAD

**Issue by qingluanchou** [QuintGao/GKNavigationBar#66]
[https://upload-images.jianshu.io/upload_images/3854055-519c2a82c2c85024.gif?imageMogr2/auto-orient/strip](url)

**Comment by QuintGao** [comment]
可以在viewWillDisappear里面将导航栏隐藏
```
- (void)viewWillDisappear:(BOOL)animated {
    [super viewWillDisappear:animated];
    
    self.navigationController.navigationBar.hidden = YES;
}
```

**Comment by qingluanchou** [comment]
这样试过，左滑的时候前一个页面的系统导航条就不见了，显示也不太好

**Comment by QuintGao** [comment]
哦 确实，我再想想怎么解决一下

**Comment by qingluanchou** [comment]
还有一个问题是UINavigationController+GKGestureHandle.m文件的151行是不是应该是写错了，应该是vc.gk_fullScreenPopDisabled吧？
        if (vc.gk_systemGestureHandleDisabled) {
            [self.panGesture removeTarget:self.systemTarget action:self.systemAction];
        }else {
            [self.panGesture addTarget:self.systemTarget action:self.systemAction];
        }

**Comment by QuintGao** [comment]
> 还有一个问题是UINavigationController+GKGestureHandle.m文件的151行是不是应该是写错了，应该是vc.gk_fullScreenPopDisabled吧？
> if (vc.gk_systemGestureHandleDisabled) {
> [self.panGesture removeTarget:self.systemTarget action:self.systemAction];
> }else {
> [self.panGesture addTarget:self.systemTarget action:self.systemAction];
> }

没错，这里是为了确定是否使用系统的手势处理

**Comment by QuintGao** [comment]
最新版增加了系统返回按钮的点击拦截，可以在这里做处理
`#pragma mark - GKGesturePopHandlerProtocol
- (BOOL)navigationShouldPopOnClick {
    self.navigationController.navigationBar.hidden = YES;
    return YES;
}`

**Comment by qingluanchou** [comment]
好的，多谢
