### ISSUE TITLE
你好，能否适配一下iPhone12 mini机型

### ISSUE THREAD

**Issue by BigKingQY** [QuintGao/GKNavigationBar#67]
我在使用iPhone12mini模拟器发现，通过代码获取到的safeAreaInsets.top = 50，而在如下方法中获取到的状态栏高度是44
详见GKNavigationBarConfigure.m第82行：

- (CGRect)gk_statusBarFrame {
    CGRect statusBarFrame = CGRectZero;
    if (@available(iOS 13.0, *)) {
        statusBarFrame = [GKConfigure getKeyWindow].windowScene.statusBarManager.statusBarFrame;
    }
    
    if (CGRectEqualToRect(statusBarFrame, CGRectZero)) {
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
        statusBarFrame = [UIApplication sharedApplication].statusBarFrame;
#pragma clang diagnostic pop
    }
    
    if (CGRectEqualToRect(statusBarFrame, CGRectZero)) {
        CGFloat statusBarH = [GKConfigure gk_isNotchedScreen] ? 44 : 20;
        statusBarFrame = CGRectMake(0, 0, GK_SCREEN_WIDTH, statusBarH);
    }
    
    return statusBarFrame;
}

总的来说，mini会多出6个点，不知道这个算不算是iOS系统bug。。请问该如何去适配这个问题？

**Comment by QuintGao** [comment]
最新版已优化
