### ISSUE TITLE
导航栏高度显示错误

### ISSUE THREAD

**Issue by wyk190576528** [QuintGao/GKNavigationBar#68]
在iPhone 12 mini 上宏GK_STATUSBAR_NAVBAR_HEIGHT为88，但self.gk_navigationBar.height获取到的是94，显示的高度确实大于88

**Comment by QuintGao** [comment]
没问题的
在iPhone 12 mini上 状态栏高度是44 顶部安全区域高度是50，系统导航栏显示的frame是{{0, 50}, {375, 44}}，所以gk_navigationBar使用的是安全区域高度+导航栏高度，比状态栏高度+导航栏高度要大

**Comment by wyk190576528** [comment]
👌
