### ISSUE TITLE
push下一个页面时候 系统导航出来后再消失

### ISSUE THREAD

**Issue by zhuanshuwx** [QuintGao/GKNavigationBar#69]

**Comment by QuintGao** [comment]
怎么配置的，我demo能复现吗？

**Comment by zhuanshuwx** [comment]
demo是正常的 但代码是一样的 跳转后系统导航栏会出现然后又隐藏

**Comment by QuintGao** [comment]
检查是不是什么地方设置导航栏显示了，或者有没有其他第三方显示了导航栏

**Comment by ZhangTonghai** [comment]
FDFullscreenPopGesture 这个库会导致这样的问题。
这个库hook了viewWillAppear方法，并调用了setNavigationBarHidden
