### ISSUE TITLE
手势被拦截

### ISSUE THREAD

**Issue by zhuanshuwx** [QuintGao/GKNavigationBar#70]
用wkweb加载链接 有的页面侧滑返回不了 以及jxpager也侧滑返回不了

**Comment by QuintGao** [comment]
我试了没问题啊 有链接可以试吗

**Comment by zhuanshuwx** [comment]
> 我试了没问题啊 有链接可以试吗

http://www.qukanvideo.com/cloud/h5/1609067279049903

**Comment by zhuanshuwx** [comment]
> 我试了没问题啊 有链接可以试吗

我发的这个试试看 demo上也是不可以的

**Comment by QuintGao** [comment]
最新版2.5.2增加了一个协议方法，返回YES就好了
