### ISSUE TITLE
导航栏渐变无效

### ISSUE THREAD

**Issue by VictDog** [QuintGao/GKNavigationBar#71]
滚动tableView， 动态修改导航栏透明度：gk_navBarAlpha或者gk_navBackgroundColor试了都无效

**Comment by QuintGao** [comment]
我试了是可以的，详见demo的UITableViewController

**Comment by VictDog** [comment]
我试了，demo是可以的， 我本地的项目就是不行， AppDelegate里面配置 GKConfigure 导航栏背景色那些都无效

**Comment by QuintGao** [comment]
导航栏能正常显示吗？看看是不是其他别的库影响的

**Comment by VictDog** [comment]
使用 self.gk_navBarAlpha = 1; 导航栏反而边透明了， 不写这句导航栏是默认的白色

**Comment by QuintGao** [comment]
你这样说我也不知道问题出在哪，最好能提供demo

**Comment by VictDog** [comment]
找到问题所在了， 在没有设置导航栏标题或者barButtonItem的情况下，确实会出现上述问题， 设置了其中某一个就正常了。

**Comment by QuintGao** [comment]
是的，如果都不设置的话_UIBarBackground不会被创建，所以某些方法是无效的
