### ISSUE TITLE
关于滑动导航显示问题！！！

### ISSUE THREAD

**Issue by Mrrabbitbaby** [QuintGao/GKNavigationBar#73]
1.有没有那种，我下拉可以这么大headerview的效果。
2.上滑动时候，如果我headerview是张图片，是否可以把导航栏改成图片？

关于这个效果，我记得好像在你的文档中见到过，但是我看了demo，并没有相关代码。

**Comment by QuintGao** [comment]
你说的应该在[GKPageScrollView](https://github.com/QuintGao/GKPageScrollView)里面
