### ISSUE TITLE
demo中有一种情况，不显示导航栏

### ISSUE THREAD

**Issue by wyk190576528** [QuintGao/GKNavigationBar#74]
![Jietu20210506-163004](https://user-images.githubusercontent.com/13128838/117267287-b4f9ff00-ae88-11eb-9454-5f49b71fa6c3.png)
![Jietu20210506-163129](https://user-images.githubusercontent.com/13128838/117267306-b9261c80-ae88-11eb-855e-7f3b08d39f90.png)

**Comment by QuintGao** [comment]
不是不显示，是_UIBarBackground没有被创建，所以设置背景色的方法无效，设置一下标题或者左右的item就好了

**Comment by QuintGao** [comment]
#71

**Comment by QuintGao** [comment]
最新版1.5.3对内部进行了修改，可以只设置背景色
