### ISSUE TITLE
gk_nonFullScreen

### ISSUE THREAD

**Issue by yulanzhu** [QuintGao/GKNavigationBar#75]
frame.origin.y = self.frame.size.height - (self.gk_nonFullScreen ? GK_NAVBAR_HEIGHT_NFS : GK_NAVBAR_HEIGHT);

此处代码 会使 导航栏 闪动一下

**Comment by QuintGao** [comment]
我demo能复现吗

**Comment by yulanzhu** [comment]
> 还是没复现，能描述下使用场景吗

1->你搜下这段代码，然后把在这里打个断点，
2->切换 tab项 切换的时候应该会卡在断点上
3->断点卡住的时候 自定义的导航栏就下来了
大牛可以加下微信吗：yuhaiming01
