### ISSUE TITLE
present的根控制器带有子控制器的bug

### ISSUE THREAD

**Issue by IAFung** [QuintGao/GKNavigationBar#78]
我又来了😃
具体显示问题可以进入demo,点击最后一个cell.
子控制器自带了导航栏,且会影响主导航栏的属性设置,如`gk_navItemRightSpace`
目前来看与
```Objective-C
[self addChildViewController:vc];
[self.view addSubview:vc.view];
```
先后添加顺序有关
[GKNavigationBar-master 2.zip](https://github.com/QuintGao/GKNavigationBar/files/6507263/GKNavigationBar-master.2.zip)

**Comment by QuintGao** [comment]
新版本已修复
