### ISSUE TITLE
崩溃 EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by VictDog** [QuintGao/GKNavigationBar#8]
![image](https://user-images.githubusercontent.com/13920746/69781725-f002f800-11e9-11ea-8ead-82949c32e93e.png)

**Comment by QuintGao** [comment]
你怎么使用的，我的demo会这样吗

**Comment by VictDog** [comment]
> 你怎么使用的，我的demo会这样吗

就是拖进去就不行，demo可以

**Comment by QuintGao** [comment]
最新版已修复
