### ISSUE TITLE
iOS10导航栏返回按钮会变形

### ISSUE THREAD

**Issue by RichardDuan** [QuintGao/GKNavigationBar#80]
公司老版本的iOS10测试机上导航栏就会被压扁

**Comment by QuintGao** [comment]
我这边用iOS 10.3.1的模拟器试了，没发现问题，你那边导航栏高度显示的是多少，另外设备的信息也给一下

**Comment by RichardDuan** [comment]
设备信息
![41622104420_ pic](https://user-images.githubusercontent.com/15153355/119793771-772d4b00-bf09-11eb-85e4-3756930c71ac.jpg)
这是测试提供的视频，我手边也没有iOS10的测试机，但是客户那边反应有这个情况
https://user-images.githubusercontent.com/15153355/119794020-b52a6f00-bf09-11eb-91dd-6c9ead60dedd.mp4

**Comment by QuintGao** [comment]
GKNavigationBar版本是多少

**Comment by RichardDuan** [comment]
> GKNavigationBar版本是多少

1.5.2

**Comment by RichardDuan** [comment]
> 升级到1.5.7再试试

新建项目是没有问题的，但是之前1.5.2升到1.5.7还是有问题

**Comment by QuintGao** [comment]
升级之后还是那样吗，返回按钮显示出来了吗

**Comment by RichardDuan** [comment]
> 升级之后还是那样吗，返回按钮显示出来了吗

一样的，没区别。会压扁而且不显示返回按钮

**Comment by QuintGao** [comment]
> > 升级到1.5.7再试试
> 
> 新建项目是没有问题的，但是之前1.5.2升到1.5.7还是有问题

新建项目没问题的话 那应该是其他地方影响的。

**Comment by RichardDuan** [comment]
> > > 升级到1.5.7再试试
> > 
> > 
> > 新建项目是没有问题的，但是之前1.5.2升到1.5.7还是有问题
> 
> 新建项目没问题的话 那应该是其他地方影
