### ISSUE TITLE
调用起系统分享后导航栏item边距失效

### ISSUE THREAD

**Issue by theskyQQ** [QuintGao/GKNavigationBar#81]
在setupDefaultConfigure方法里把self.gk_navItemLeftSpace、self.gk_navItemRightSpace、self.navItemLeftSpace、self.navItemRightSpace都设置以后就不会失效
![Simulator Screen Shot - iPhone 11 Pro Max - 2021-05-27 at 11 07 11](https://user-images.githubusercontent.com/43028510/119760356-6ca88c80-bedc-11eb-843a-f28bda659144.png)

**Comment by QuintGao** [comment]
configure.shiledItemSpaceVCs = @[@"UIActivityViewController", @"UIActivityContentViewController"];
设置下屏蔽的控制器就好了
