### ISSUE TITLE
阿拉伯语环境下(RightToLeft)滑动返回以及屏幕边缘滑动返回失效

### ISSUE THREAD

**Issue by rhwish** [QuintGao/GKNavigationBar#83]

**Comment by QuintGao** [comment]
没失效啊 我测试是可以的，你可以用我demo试试

**Comment by rhwish** [comment]
demo我测试过滑动返回确实没问题，但是在阿拉伯语环境下push应该从左往右展示的。

**Comment by rhwish** [comment]
demo我测试过滑动返回确实没问题，但是在阿拉伯语环境下push应该从左往右展示的。

再就是我这边项目国际化后在阿拉伯语环境下push已变成从左往右展示，但是此时左滑返回失效，需要先右滑一小块距离再接着左滑才能触发返回，这个问题是不是手势在阿拉伯语环境下也需要适配

**Comment by QuintGao** [comment]
你是怎么配置的，最好能提供复现的demo
