### ISSUE TITLE
能给源代码吗 ？在pod上改不太好啊

### ISSUE THREAD

**Issue by caojian1235** [QuintGao/GKNavigationBar#85]
希望能跳转的时候隐藏 tabbar, 在pushViewController 方法里面加一句if (self.childViewControllers.count > 0) {
        // push 时隐藏 tabBar
        viewController.hidesBottomBarWhenPushed = YES;
    }

**Comment by QuintGao** [comment]
可以自己添加一个UINavigationController的分类然后做处理，不需要在pod上改
