### ISSUE TITLE
关于有关冲突问题

### ISSUE THREAD

**Issue by kite424** [QuintGao/GKNavigationBar#87]
我在有TZImagePickerController的框架下，使用gknavigationBar框架的时候，将会造成使用tz的框架发生此问题。我想问的是，没有使用此框架的任何方法的时候，为啥会影响其他框架的使用？
---1.第一张是在有gknavigationBar框架的情况下，没有任何使用，直接会造成TZImagePickerController的左右两边的navigationbar间距为0
---2.第二张是在没有gknavigationBar框架的情况下，不会有影响。

我想要解决的问题是：没有使用gknavigationBar的时候，不会有影响，使用gknavigationBar的时候，才会有影响。

<img width="373" alt="1" src="https://user-images.githubusercontent.com/57931594/126284010-48bca065-f604-4c76-b016-ce97d61d99d2.png">
![2](https://user-images.githubusercontent.com/57931594/126283821-dac4b1dc-6fcc-4446-8065-912602af7000.jpg)

**Comment by kite424** [comment]
![2](https://user-images.githubusercontent.com/57931594/126285652-aec51ddc-08c5-40c1-a941-4fc6a06ad3bb.jpg)

**Comment by QuintGao** [comment]
设置一下需要屏蔽的控制器就可以了shiledItemSpaceVCs
