### ISSUE TITLE
侧滑返回，TabBar显示异常

### ISSUE THREAD

**Issue by dwjgkp** [QuintGao/GKNavigationBar#90]
复现步骤：
1、网易新闻第一个Tab“首页”的页面点击事件
2、打开的新闻详情页面增加属性gk_systemGestureHandleDisabled为YES
`- (void)pageAction {`
    `GKWYNewsDetailViewController *detailVC = [GKWYNewsDetailViewController new];`
   ` detailVC.gk_systemGestureHandleDisabled = YES;`
    `detailVC.hidesBottomBarWhenPushed = YES;`
   ` [self.navigationController pushViewController:detailVC animated:YES];`
`}`
3、从详情页面侧滑返回，此时TabBar会出现在详情页面上方，位置错乱

**Comment by QuintGao** [comment]
照着你说的修改试过了，没发现问题，能否提供错误截图及demo

**Comment by dwjgkp** [comment]
> 照着你说的修改试过了，没发现问题，能否提供错误截图及demo

[GKNavigationBar反馈内容.zip](https://github.com/QuintGao/GKNavigationBar/files/7493912/GKNavigationBar.zip)
demo及错误录屏

**Comment by QuintGao** [comment]
最新版已修复
