### ISSUE TITLE
gk_navItemRightSpace存在无效的情况，可查看demo效果

### ISSUE THREAD

**Issue by wyk190576528** [QuintGao/GKNavigationBar#91]
版本：1.6.0
SubViewController中，self.gk_navigationBar.hidden = YES;注释的话，就没问题，不注释，gk_navItemRightSpace无效
[demo.zip](https://github.com/QuintGao/GKNavigationBar/files/7481606/demo.zip)

**Comment by QuintGao** [comment]
子控制器一般情况下是不需要导航栏的，如果一定要创建导航栏的话，最好设置下子控制器的gk_navItemRightSpace与父控制器相同
