### ISSUE TITLE
可以适配一下iOS15吗

### ISSUE THREAD

**Issue by VictDog** [QuintGao/GKNavigationBar#92]
大佬，可以适配一下iOS 15吗？  导航栏透明的情况下，滑动视图，导航栏阴影线就显示出来了， 根据网上的做法，设置了scrollEdgeAppearance 和 standardAppearance 还是不行

**Comment by QuintGao** [comment]
怎么使用的 我这边没复现

**Comment by VictDog** [comment]
就是普通用法 self.gk_navBackgroundColor = [UIColor clearColor];   self.gk_navLineHidden = YES; 然后滑动tableView 导航栏的阴影线就显示出来了

**Comment by QuintGao** [comment]
可以提供测试demo吗，我这边试没出现
