### ISSUE TITLE
您好 轮子哥  打印机、系统分享界面上面的导航按钮会有偏移 能给修复下嘛

### ISSUE THREAD

**Issue by leeJPOnly** [QuintGao/GKNavigationBar#95]
打印机、系统分享 界面是系统的导航栏，设置gk_navItemLeftSpace、shiledItemSpaceVCs 等参数，都不能恢复（打印机、系统分享）的导航按钮便宜问题，麻烦有空的下，给修复下哈

**Comment by leeJPOnly** [comment]
![Simulator Screen Shot - iPhone 13 - 2022-02-22 at 18 58 34](https://user-images.githubusercontent.com/20916883/155123111-4e1d04e4-c508-4f48-94f9-b7adc320a557.png)

**Comment by leeJPOnly** [comment]
<img width="291" alt="WeChat8c361bd14e85f4e653ac717fef641114" src="https://user-images.githubusercontent.com/20916883/155123369-9d7ed148-d7ff-42f8-8654-434818bc4ed2.png">

**Comment by QuintGao** [comment]
最新版已优化

**Comment by leeJPOnly** [comment]
谢谢了
