### ISSUE TITLE
GKNavigationBar和TZImagePickerController公用的时候会有一些问题

### ISSUE THREAD

**Issue by qq274936784** [QuintGao/GKNavigationBar#98]
配置初始化已经设置了GKConfigure.shiledItemSpaceVCs = @[@"TZImagePickerController",@"TZPhotoPickerController"];
但是在其它页面弹出TZImagePickerController后,再次进入该页面就会出现导航栏左右按钮位置偏移问题

**Comment by QuintGao** [comment]
升级到1.7.0以上试试，shiledItemSpaceVCs这个属性已经移除了

**Comment by qq274936784** [comment]
已经更新到1.7.1最新,问题得到解决,感谢大佬
